### PR TITLE
allow multiple files using glob pattern

### PR DESCRIPTION
**Pull request by kopax**
This PR add the following feature : 

- glob pattern for `<file>` is allowed.
- added `-s` (soft mode) to prevent fail on missing TOC.

### CODE REVIEW

**Comment by n1k0** [comment]
Thanks, looks great and useful!

One thing though, it would be nice to allow passing just the plain name of an existing folder; right now it gives a weird error, which may be disturbing:

```
➜  toctoc git:(c1b8292) ✗ bin/toctoc.js tmp
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at readFile (/home/niko/work/toctoc/bin/toctoc.js:51:13)
    at files.forEach (/home/niko/work/toctoc/bin/toctoc.js:97:29)
    at Array.forEach (<anonymous>)
    at /home/niko/work/toctoc/bin/toctoc.js:92:9
    at f (/home/niko/work/toctoc/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/niko/work/toctoc/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
```

We should probably attempt at treating the arg as a folder name, then fallback on using the glob pattern methinks. Also we should/try/catch these operations and expose human-friendly error messages instead of stack exceptions.

Would you be willing to update the patch accordingly? If not I can take care of that.

Thanks for contributing 👍

**Comment by kopax** [comment]
> We should probably attempt at treating the arg as a folder name, then fallback on using the glob pattern 

Hi, I have just updated the commit with the requested change. I have added a default extension to be used when using a directory. I guess it is better than reading every files by default.

I have tested and it appear the glob will still fail. But that's the way your script is written at the first place, not supposed to handle multiple cases.

**Comment by kopax** [comment]
I have also corrected examples from `README.md` where `-w` argument should be after `<file>`

**Review by n1k0 — APPROVED** [review]
Great work, thank you!

**Pull request merged**
